# Numpy

In [1]:
import numpy as np

### 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [2]:
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

### 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

In [3]:
arr=np.random.random((3, 3, 3))
print(arr)
print('Min : ',arr.min())
print('Max : ',arr.max())

[[[0.72069633 0.86835631 0.74550302]
  [0.73676602 0.60900466 0.51916978]
  [0.83575491 0.91328603 0.67279337]]

 [[0.59184285 0.12543217 0.21961908]
  [0.62872919 0.60539696 0.30889255]
  [0.38908811 0.09397913 0.05560883]]

 [[0.68541647 0.27442674 0.44134932]
  [0.5393271  0.2056415  0.60016648]
  [0.77481993 0.3192923  0.73185279]]]
Min :  0.05560883413411832
Max :  0.9132860283252662


### 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [4]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 4. Given an array
- arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
- i) Extract all odd numbers from arr
- ii) Replace all odd numbers in arr with -1

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('Original array: ',arr)
print('Odd numbers array: ',arr[arr%2!=0])
arr[arr%2!=0] = -1
print('Odd numbers relaced with -1: ',arr)

Original array:  [0 1 2 3 4 5 6 7 8 9]
Odd numbers array:  [1 3 5 7 9]
Odd numbers relaced with -1:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 5. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 6. Write a NumPy program to convert an array to a float type.

In [7]:
np.array([1, 2, 3, 4],dtype='float')

array([1., 2., 3., 4.])

### 7. Write a NumPy program to generate five random numbers from the normal distribution.

In [8]:
np.random.randn(5)

array([ 0.83464899, -1.0233109 ,  0.29203284, -0.15697962,  0.58520501])

### 8. Following is the input NumPy array delete column two and insert following new column in its place.
- sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]])
- newColumn = numpy.array([[10,10,10]])

In [9]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 2]=newColumn
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

### 9. Write a NumPy program to compute the multiplication of two given matrices.

In [10]:
mat1 =np.arange(1,7).reshape(2,3)
mat2 =np.arange(1,7).reshape(3,2)
np.dot(mat1,mat2)

array([[22, 28],
       [49, 64]])

### 10. Write a NumPy program to create a random vector of size 10 and sort it.

In [11]:
np.sort(np.random.randint(1,50,size=10))

array([ 1,  2, 11, 11, 16, 16, 30, 30, 43, 48])

### 11. Write a NumPy program to compute the covariance matrix of two arrays.

In [12]:
mat1 =np.random.randint(1,10,size=3)
mat2 =np.random.randint(1,10,size=3)
print(mat1)
print(mat2)
print('Covariance matrix:\n',np.cov(mat1,mat2))

[9 9 1]
[4 7 1]
Covariance matrix:
 [[21.33333333 12.        ]
 [12.          9.        ]]


### 12.Create a 4X2 integer array and Prints its :
- i)The shape of an array.
- ii) Array dimensions.
- iii) The Length of each element of the array in bytes

In [13]:
mat1 =np.random.randint(1,10,size=[4,2])
print(mat1.shape)
print(mat1.ndim)
print(mat1.nbytes)

(4, 2)
2
32


### 13. Write a NumPy program to concatenate element-wise two arrays of string.

In [14]:
arr1=np.array(['a','b','c'])
arr2=np.array(['x','y','z'])
print( np.char.add(arr1,arr2))

['ax' 'by' 'cz']


### 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [15]:
arr1=np.array(['Hulk','Iron Man','Captain America','Thor'])
print (np.char.capitalize(arr1))
print (np.char.lower(arr1))
print (np.char.upper(arr1))
print (np.char.swapcase(arr1))
print (np.char.title(arr1))

['Hulk' 'Iron man' 'Captain america' 'Thor']
['hulk' 'iron man' 'captain america' 'thor']
['HULK' 'IRON MAN' 'CAPTAIN AMERICA' 'THOR']
['hULK' 'iRON mAN' 'cAPTAIN aMERICA' 'tHOR']
['Hulk' 'Iron Man' 'Captain America' 'Thor']


### 15. Write a NumPy program to convert a given array into a list.

In [16]:
arr=np.arange(0,10).reshape(5,2)
print('Numpy Array:\n',arr)
print('List:\n',arr.tolist())

Numpy Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
List:
 [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]


### 16. Write a NumPy program to compute the sum of all elements,  sum of each column and sum of each row of a given array.

In [17]:
arr =np.random.randint(1,20,size=[4,3])
print('Array:\n',arr)
print('Sum of all elements:\n',np.sum(arr))
print('sum of each column:\n',np.sum(arr,axis=0))
print('sum of each row:\n',np.sum(arr,axis=1))

Array:
 [[15 12 18]
 [ 5  9 19]
 [ 1  2 16]
 [11 16 19]]
Sum of all elements:
 143
sum of each column:
 [32 39 72]
sum of each row:
 [45 33 19 46]


### 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [18]:
arr =np.random.randint(0,40,size=[10,4])
arr1=arr[:5,:]
print('Original array:\n',arr)
print('Top 5 rows:\n',arr1)

Original array:
 [[26 15 19  3]
 [36  1 35  8]
 [ 3 22 37 16]
 [21 18 39 16]
 [30 22 32 38]
 [10 24 24  8]
 [31 32  1 11]
 [ 8 37 26 27]
 [14  6  9  5]
 [29 21 31  0]]
Top 5 rows:
 [[26 15 19  3]
 [36  1 35  8]
 [ 3 22 37 16]
 [21 18 39 16]
 [30 22 32 38]]


### 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

In [19]:
arr1 =np.random.randint(0,3,size=4)
arr2 =np.random.randint(0,10,size=[3,4])
print('1d array:\n',arr1)
print('Unique elements of 1d array:\n',np.unique(arr1))
print('2d array:\n',arr2)
print('Unique elements of 2d array:\n',np.unique(arr2))

1d array:
 [1 0 0 0]
Unique elements of 1d array:
 [0 1]
2d array:
 [[6 7 3 6]
 [6 9 2 7]
 [2 7 3 3]]
Unique elements of 2d array:
 [2 3 6 7 9]


### 19. Write a NumPy program to get the unique elements of an array.
- arr= [ -10 12.12 -0.2]

In [20]:
arr= [-10,12.,12,-0.2]
print(np.unique(arr))

[-10.   -0.2  12. ]


### 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library

In [21]:
np.savetxt('df.txt',np.random.randint(0,10,size=[3,4]))
arr = np.loadtxt('df.txt')
print(arr)

[[4. 7. 6. 4.]
 [8. 0. 0. 6.]
 [1. 2. 7. 6.]]
