1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10¶

In [2]:
import numpy as np


In [4]:
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

In [5]:
arr=np.random.random((3, 3, 3))
print(arr)
print('Min : ',arr.min())
print('Max : ',arr.max())

[[[0.44860637 0.59296664 0.2405692 ]
  [0.62747223 0.67827372 0.70362798]
  [0.54943309 0.58324859 0.36436333]]

 [[0.23631353 0.4515198  0.04844675]
  [0.02003461 0.38757139 0.65219898]
  [0.63284203 0.39549301 0.62883456]]

 [[0.66181486 0.35967831 0.50571594]
  [0.63556741 0.41134628 0.21644958]
  [0.97482283 0.01757348 0.54449011]]]
Min :  0.017573479529162772
Max :  0.9748228299654745


3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [6]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

4. Given an array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
i) Extract all odd numbers from arr
ii) Replace all odd numbers in arr with -1

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
print('Odd numbers array: ',arr[arr%2!=0])
arr[arr%2!=0] = -1
print('Odd numbers relaced with -1: ',arr)

[0 1 2 3 4 5 6 7 8 9]
Odd numbers array:  [1 3 5 7 9]
Odd numbers relaced with -1:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Write a NumPy program to convert an array to a float type.

In [10]:
np.array([1, 2, 3, 4],dtype='float')

array([1., 2., 3., 4.])

Write a NumPy program to generate five random numbers from the normal distribution.

In [11]:
np.random.randn(5)

array([-1.20343972,  0.40008719,  0.24116694,  1.39462064, -0.38452431])

8. Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

In [13]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 2]=newColumn
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

Write a NumPy program to compute the multiplication of two given matrices.

In [17]:
p = [[2, 4], [0, 1]]
q = [[1, 3], [5, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)


original matrix:
[[2, 4], [0, 1]]
[[1, 3], [5, 4]]
Result of the said matrix multiplication:
[[22 22]
 [ 5  4]]


### 10. Write a NumPy program to create a random vector of size 10 and sort it.

In [18]:
np.sort(np.random.randint(1,50,size=10))

array([ 1, 14, 16, 18, 20, 22, 34, 35, 37, 39])

### 11. Write a NumPy program to compute the covariance matrix of two arrays.

In [20]:
num1 =np.random.randint(1,7,size=3)
num2 =np.random.randint(1,8,size=3)
print(num1)
print(num2)
print('Covariance matrix:\n',np.cov(num1,num2))

[2 4 4]
[4 7 1]
Covariance matrix:
 [[1.33333333 0.        ]
 [0.         9.        ]]


### 12.Create a 4X2 integer array and Prints its :
- i)The shape of an array.
- ii) Array dimensions.
- iii) The Length of each element of the array in bytes

In [23]:
arr1 =np.random.randint(1,10,size=[4,2])
print(arr1.shape)
print(arr1.ndim)
print(arr1.nbytes)

(4, 2)
2
32


Write a NumPy program to concatenate element-wise two arrays of string.

In [24]:
arr1=np.array(['a','b','c'])
arr2=np.array(['x','y','z'])
print( np.char.add(arr1,arr2))

['ax' 'by' 'cz']


### 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [25]:
arr1=np.array(['Abhilash','Anu','Geetha','Koshin'])
print (np.char.capitalize(arr1))
print (np.char.lower(arr1))
print (np.char.upper(arr1))
print (np.char.swapcase(arr1))
print (np.char.title(arr1))

['Abhilash' 'Anu' 'Geetha' 'Koshin']
['abhilash' 'anu' 'geetha' 'koshin']
['ABHILASH' 'ANU' 'GEETHA' 'KOSHIN']
['aBHILASH' 'aNU' 'gEETHA' 'kOSHIN']
['Abhilash' 'Anu' 'Geetha' 'Koshin']


### 15. Write a NumPy program to convert a given array into a list.

In [26]:
arr=np.arange(0,10).reshape(5,2)
print('Numpy Array:\n',arr)
print('List:\n',arr.tolist())

Numpy Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
List:
 [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]


### 16. Write a NumPy program to compute the sum of all elements,  sum of each column and sum of each row of a given array.

In [27]:
arr =np.random.randint(1,20,size=[4,3])
print('Array:\n',arr)
print('Sum of all elements:\n',np.sum(arr))
print('sum of each column:\n',np.sum(arr,axis=0))
print('sum of each row:\n',np.sum(arr,axis=1))

Array:
 [[ 4 13 10]
 [16 11  1]
 [12  1 16]
 [15 15 12]]
Sum of all elements:
 126
sum of each column:
 [47 40 39]
sum of each row:
 [27 28 29 42]


### 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [28]:
arr =np.random.randint(0,40,size=[10,4])
arr1=arr[:5,:]
print('Original array:\n',arr)
print('Top 5 rows:\n',arr1)

Original array:
 [[15 24 14 38]
 [20 32 36  0]
 [20 28 22 36]
 [37 22 24 29]
 [38 22  6 14]
 [ 0 23 15 19]
 [28 34 21 33]
 [ 9  6 36 39]
 [ 2 32  4  8]
 [31 30 27 34]]
Top 5 rows:
 [[15 24 14 38]
 [20 32 36  0]
 [20 28 22 36]
 [37 22 24 29]
 [38 22  6 14]]


### 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

In [29]:
arr1 =np.random.randint(0,3,size=4)
arr2 =np.random.randint(0,10,size=[3,4])
print('1d :\n',arr1)
print('Unique elements of 1d array:\n',np.unique(arr1))
print('2d array:\n',arr2)
print('Unique elements of 2d array:\n',np.unique(arr2))

1d :
 [0 0 2 1]
Unique elements of 1d array:
 [0 1 2]
2d array:
 [[1 0 8 4]
 [6 7 4 8]
 [7 8 0 6]]
Unique elements of 2d array:
 [0 1 4 6 7 8]


### 19. Write a NumPy program to get the unique elements of an array.
- arr= [ -10 12.12 -0.2]

In [30]:
arr= [-10,12.,12,-0.2]
print(np.unique(arr))

[-10.   -0.2  12. ]


### 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library

In [31]:
np.savetxt('df.txt',np.random.randint(0,10,size=[3,4]))
arr = np.loadtxt('df.txt')
print(arr)

[[9. 9. 9. 0.]
 [6. 5. 8. 0.]
 [1. 2. 5. 1.]]
