In [ ]:
# Agenda
# What is pandas
# What is series
#Installation of Pandas
#Create Simple Series
# Create Series from Numpy
#Create Series with custom indexes
#Filter series based on the conditions
#Check whether elements is in the series
#to_dict() functions
#Intro to NAN
#Intro to NULL
#addition of two series


### pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license. The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals. Its name is a play on the phrase "Python data analysis" itself. Wes McKinney started building what would become pandas at AQR Capital while he was a researcher there from 2007 to 2010.

In [3]:
!pip install pandas

In [4]:
import numpy as np
import pandas as pd

In [6]:
# What is pandas
# What is a series

import pandas as pd
from pandas import Series

In [7]:
#Create Simple Series

S1= Series([5,10,15,20])
print(S1)

0     5
1    10
2    15
3    20
dtype: int64


In [9]:
print(S1.values)

[ 5 10 15 20]


In [10]:
print(S1.index.values)

[0 1 2 3]


In [11]:
# Create Series from Numpy
revenue_array =np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [13]:
revenue_Series=Series(revenue_array)
print(revenue_Series)

0    400
1    300
2    200
3    100
dtype: int32


In [14]:
#Create Series with custom indexes
revenue = Series (revenue_array,index=['Uber','OLA','Gojeck','Lyft'])
print(revenue)

Uber      400
OLA       300
Gojeck    200
Lyft      100
dtype: int32


In [16]:
revenue['OLA']

300

In [17]:
revenue['Lyft']

100

In [18]:
#Filter series based on the conditions
print(revenue>250)

Uber       True
OLA        True
Gojeck    False
Lyft      False
dtype: bool


In [19]:
print(revenue[revenue>250])

Uber    400
OLA     300
dtype: int32


In [20]:
#Check whether elements is in the series
print('OLA' in revenue)

True


In [21]:
print('GRAB' in revenue)

False


In [23]:
#to_dict() functions
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'Uber': 400, 'OLA': 300, 'Gojeck': 200, 'Lyft': 100}


In [24]:
# addition of two series
print(revenue)

Uber      400
OLA       300
Gojeck    200
Lyft      100
dtype: int32


In [25]:
print(revenue+revenue)

Uber      800
OLA       600
Gojeck    400
Lyft      200
dtype: int32


In [26]:
# Assign Names to a series

revenue.name="Company-Revenue"
revenue.index.name="Company Name"
print (revenue)



Company Name
Uber      400
OLA       300
Gojeck    200
Lyft      100
Name: Company-Revenue, dtype: int32
